Revert "Remove snyk from publish step in CircleCI temporarily"
Financial-Times/x-dash pull request #536
Opened 2020-10-07 15:39 UTC by tbergmen

This reverts commit 7debe342de326e0f39e5452c94146fb1bac96143.

2020-10-12 09:15 UTC, andygout approved these changes

2020-10-19 13:27 UTC, antonsamper approved these changes

2020-10-28 08:27 UTC, andygout requested changes
As per https://github.com/Financial-Times/next-fastly-to-graphite/pull/62, we will likely need to add ` --prune-repeated-subdependencies` to make this work.

2020-10-28 08:52 UTC, andygout submitted a review, later dismissed

2020-10-28 09:02 UTC, andygout submitted a review, later dismissed

2020-10-28 09:11 UTC, andygout approved these changes

2020-10-28 09:11 UTC, merged