WIP: share highlight preview when copying a link
Financial-Times/x-dash pull request #787
Opened 2024-10-16 10:26 UTC by ibrahim-mamdouh-ft

If this is your first `x-dash` pull request please familiarise yourself with the [contribution guide](https://github.com/Financial-Times/x-dash/blob/HEAD/contribution.md) before submitting.

## If you're creating a component:

- Add the `Component` label to this Pull Request
- If this will be a long-lived PR, consider using smaller PRs targeting this branch for individual features, so your team can review them without involving x-dash maintainers
  - If you're using this workflow, create a Label and a Project for your component and ensure all small PRs are attached to them. Add the Project to the [Components board](https://github.com/Financial-Times/x-dash/projects/4)
    - put a link to this Pull Request in the Project description
    - set the Project to `Automated kanban with reviews`, but remove the `To Do` column
  - If you're not using this workflow, add this Pull Request to the [Components board](https://github.com/Financial-Times/x-dash/projects/4).

## 

- Discuss features first
- Update the documentation
- **Must** be tested in FT.com and Apps before merge
- No hacks, experiments or temporary workarounds
- Reviewers are empowered to say no
- Reference other issues
- Update affected stories and snapshots
- Follow the code style
- Decide on a version (major, minor, or patch)

2024-10-25 10:45 UTC, ytcleon commented
**Change request**: Would be nice to update the properties section in the [README](https://github.com/Financial-Times/x-dash/blob/main/components/x-gift-article/readme.md)

2024-10-25 10:46 UTC, ytcleon requested changes
The changes looks good to me. Will approve after the README is updated.

2024-10-30 11:48 UTC, ibrahim-mamdouh-ft commented
Hello @ytcleon I have updated readme file

2024-10-30 16:22 UTC, ytcleon approved these changes

2024-10-30 22:28 UTC, merged